FROM python:3.10.3-alpine3.14

WORKDIR /app
COPY ./ ./

RUN apk add --no-cache --virtual .build-deps g++ python3-dev libffi-dev openssl-dev && \
    apk add --no-cache --update python3 

RUN pip install --upgrade pip
RUN yes | pip install -r requirements.txt
RUN chmod +x ./flask-run.sh

CMD ["python","-u","./app.py"]

